services:
  easy-links:
    image: easy-homepage
    container_name: easy-homepage
    ports:
      - "3000:3000"
    volumes:
      - ./public/icons:/app/public/icons
      - ./data:/data
    environment:
      - LOGO_DEV_API_KEY=${LOGO_DEV_API_KEY}
      # Uncomment the next line for local file mode:
      # - SITES_JSON_PATH=/data/private.json
      - GITHUB_OWNER=armand-janssen
      - GITHUB_REPO_NAME=my-config
      - GITHUB_FILE_PATH=homepage/private.json
      - GITHUB_TOKEN=${GITHUB_MY_CONFIG_READER_TOKEN}
